jiras = {
    'Apache': {'url': 'https://issues.apache.org/jira', 'username': '', 'password': ''},
    'Hyperledger': {'url': 'https://jira.hyperledger.org', 'username': '', 'password': ''},
    'DAOS': {'url': 'https://daosio.atlassian.net/jira/', 'username': '', 'password': ''},
    'JFrog': {'url': 'https://www.jfrog.com/jira', 'username': '', 'password': ''},
    'JIRA': {'url': 'https://jira.atlassian.com/secure/', 'username': '', 'password': ''},
    'JIRAEcosystem': {'url': 'https://ecosystem.atlassian.net/jira/', 'username': '', 'password': ''},
    'MongoDB': {'url': 'https://jira.mongodb.org', 'username': '', 'password': ''},
    'QT': {'url': 'https://bugreports.qt.io', 'username': '', 'password': ''},
    'RedHat': {'url': 'https://issues.redhat.com/', 'username': '', 'password': ''},
    'Sakai': {'url': 'https://sakaiproject.atlassian.net/jira', 'username': '', 'password': ''},
    'SecondLife': {'url': 'https://jira.secondlife.com', 'username': '', 'password': ''},
    'Sonatype': {'url': 'https://issues.sonatype.org/', 'username': '', 'password': ''},
    'Spring': {'url': 'https://jira.spring.io', 'username': '', 'password': ''},
    'Vivo': {'url': 'https://vivo-project.atlassian.net/jira', 'username': '', 'password': ''},
    'Islandora': {'url': 'https://islandora-legacy.atlassian.net/jira', 'username': '', 'password': ''},
    'Fedora': {'url': 'https://fedora-repository.atlassian.net/jira', 'username': '', 'password': ''},
    'Duracloud': {'url': 'https://duracloud.atlassian.net/jira', 'username': '', 'password': ''},
    'Talendforge': {'url': 'https://jira.talendforge.org', 'registration': 'no'},
    'template': {'url': '', 'username': '', 'password': ''},
    'template': {'url': '', 'username': '', 'password': ''},
    'template': {'url': '', 'username': '', 'password': ''},
    'template': {'url': '', 'username': '', 'password': ''},
    'template': {'url': '', 'username': '', 'password': ''},
    'template': {'url': '', 'username': '', 'password': ''},
    'template': {'url': '', 'username': '', 'password': ''}
}